Eapp 20 create team section subpages
mariyaniliev/ERP-App pull request #23
Opened 2022-03-29 10:14 UTC by LyubooShv

2022-03-29 10:33 UTC, mariyaniliev commented on src/pages/Team/TeamSection.tsx
> +  const dispatch = useAppDispatch();
use the bind dispatch method

2022-03-29 10:33 UTC, mariyaniliev commented on src/pages/Team/TeamSection.tsx
> +  ] as const;
This looks pretty good.
Move it to a separate folder (service) for navigation

2022-03-30 09:31 UTC, Georgi07 requested changes

2022-03-30 09:31 UTC, Georgi07 commented on src/pages/Team/TeamSection.tsx
> +import { Box } from "@mui/system";
import Box from "@mui/material" instead of "@mui/system"

2022-03-30 09:31 UTC, Georgi07 commented on src/pages/Team/teamSection-styles.ts
> +  borderBottom: `2px solid rgba(0, 0, 0, 0.1)`,
Change border bottom to 3px because it is consistant with bottom purple line when tab is selected.

2022-03-30 09:31 UTC, Georgi07 commented on src/pages/Team/teamSection-styles.ts
> +  fontFamily: "Open Sans, sans-serif", //does not get fontFamily from the theme provider
Just delete the comment

2022-03-30 09:31 UTC, Georgi07 commented on src/pages/Home/Home.tsx
>      <div>
Use "Box" instead div.

2022-03-30 09:31 UTC, Georgi07 commented on src/pages/Team/teamSection-styles.ts
> +export const StyledTabs = styled(TabsUnstyled)({
Delete all styles except padding. Add padding: "30px 25px 20px 25px".

2022-03-30 09:31 UTC, Georgi07 commented on src/pages/Team/teamSection-styles.ts
> +export const StyledTabs = styled(TabsUnstyled)({
Delete style for TabsUnstyled because all styles are unnecessary.

2022-03-30 09:31 UTC, Georgi07 commented on src/pages/Team/TeamSection.tsx
> +const TeamSection = () => {
Change file name, function  and folder to "Team"

2022-03-30 09:31 UTC, Georgi07 commented on src/pages/Team/teamSection-styles.ts
> +});
export all styled components like that:
export { StyledTabs, StyledTabsList, StyledTab };

Change file name to be "team-styles.ts"

2022-03-30 09:31 UTC, Georgi07 commented on src/pages/Team/teamSection-styles.ts
> +});
export all styled components like that:
export { StyledTabs, StyledTabsList, StyledTab };

2022-03-30 11:33 UTC, merged